# Generated by Django 4.2.19 on 2026-02-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='predicted_default_risk',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='loan',
            name='risk_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
