# Generated by Django 4.2.19 on 2025-12-25 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="age",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="client",
            name="employment_type",
            field=models.CharField(default="Salaried", max_length=50),
        ),
        migrations.AddField(
            model_name="loan",
            name="collateral_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="loan",
            name="days_past_due",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loan",
            name="missed_payments",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="loan",
            name="monthly_emi",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="loan",
            name="outstanding_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="loan",
            name="tenure",
            field=models.IntegerField(default=12, help_text="Months"),
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.TextField(default="Unknown"),
        ),
        migrations.AlterField(
            model_name="client",
            name="contact",
            field=models.CharField(default="Unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="client",
            name="financial_score",
            field=models.IntegerField(default=600, help_text="Credit Score (300-850)"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="amount",
            field=models.FloatField(help_text="Loan Amount"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="loan",
            name="predicted_default_risk",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="risk_explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="method",
            field=models.CharField(default="SMS", max_length=10),
        ),
    ]
