# Generated by Django 4.2.19 on 2025-12-27 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_client_age_client_employment_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("Email", "Email"),
                            ("Call", "Phone Call"),
                            ("Visit", "Physical Visit"),
                            ("Legal", "Legal Action"),
                        ],
                        max_length=20,
                    ),
                ),
                ("officer_notes", models.TextField()),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="core.loan",
                    ),
                ),
            ],
        ),
    ]
