# Generated by Django 4.2.19 on 2026-03-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_address_client_email_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
