# Generated by Django 4.2.19 on 2026-03-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='risk_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
